# Generated by Django 5.1.5 on 2025-01-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='no_of_guests',
        ),
    ]
