# Generated by Django 5.1.5 on 2025-01-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonApp', '0002_rename_guests_booking_no_of_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
